-intstyle "ise" -incremental -lib "secureip" -o "D:/Ali Yazdi/Documents/GitHub/Architecture_Project/stb_isim_beh.exe" -prj "D:/Ali Yazdi/Documents/GitHub/Architecture_Project/stb_beh.prj" "work.stb" 
